version: '3'
services:
  playground:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: playground
    privileged: true
    volumes:
      - ./build-folder/:/opt/build-directory/

